# -*- coding: utf-8 -*-
"""Untitled.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A7MJYC1A0l-Ow7Jaw7jFyMIY5wIGUfrz
"""

import os
import zipfile
import random
import shutil
import glob
from pathlib import Path
import matplotlib.pyplot as plt
from PIL import Image

import torch
from torchvision import transforms, datasets
from torch.utils.data import DataLoader

# =====================================================================
# [1단계] 환경 세팅 및 난수 시드 고정
# =====================================================================
# (코랩 전용 구글 드라이브 마운트 및 %cd 명령어 삭제 완료)

# 난수 시드 고정 (재현성 확보)
def set_seed(seed=42):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False

set_seed(42)
print("✅ 로컬 환경 난수 시드(42) 고정 완료.")

# =====================================================================
# [2단계] 경로 설정 및 클래스 매핑
# =====================================================================
# 로컬 환경에 맞게 상대 경로(./)로 수정 완료
ZIP_SOURCE_DIR = './AI_Project'                 # zip 파일들이 모여있는 폴더 (현재 폴더 안의 AI_Project)
EXTRACT_DIR = './raw_extracted'                 # 임시 압축 해제 폴더
SUBSET_DIR = './agricultural_qc_subset'         # 최종 분할 저장될 폴더

# 10대 대분류 품목 매핑 룰
CLASS_MAPPING = {
    'apple': 'Apple',
    'cabbage_green': 'Cabbage', 'cabbage_red': 'Cabbage', 'cabbage red': 'Cabbage',
    'chinese-cabbage': 'Chinese-cabbage',
    'garlic_uiseong': 'Garlic',
    'mandarine_hallabong': 'Mandarine', 'mandarine_onjumilgam': 'Mandarine',
    'onion_red': 'Onion', 'onion_white': 'Onion',
    'pear_chuhwang': 'Pear', 'pear_singo': 'Pear',
    'persimmon_bansi': 'Persimmon', 'persimmon_booyu': 'Persimmon', 'persimmon_deabong': 'Persimmon',
    'potato_seolbong': 'Potato', 'potato_sumi': 'Potato',
    'radish_winter-radish': 'Radish'
}

# =====================================================================
# [3단계] 스마트 압축 해제 (중복 실행 방지)
# =====================================================================
os.makedirs(EXTRACT_DIR, exist_ok=True)
zip_files = [f for f in os.listdir(ZIP_SOURCE_DIR) if f.endswith('.zip')]

print("\n1. 압축 해제 확인.")
for z_file in zip_files:
    zip_name_lower = z_file.lower()
    matched_class = None

    for rule, main_class in CLASS_MAPPING.items():
        if rule in zip_name_lower:
            matched_class = main_class
            break

    if matched_class:
        target_extract_path = os.path.join(EXTRACT_DIR, f"{matched_class}_{Path(z_file).stem}")

        if os.path.exists(target_extract_path) and os.listdir(target_extract_path):
            print(f"'{z_file}'은(는) 이미 압축 해제되어 있습니다.")
            continue

        print(f"'{z_file}' 압축을 푸는 중입니다.")
        with zipfile.ZipFile(os.path.join(ZIP_SOURCE_DIR, z_file), 'r') as zip_ref:
            zip_ref.extractall(target_extract_path)

print("✅ 압축 해제 확인 완료!")

# =====================================================================
# [4단계] 세부 품종/품질 층화 추출 및 샘플링 후 검증
# =====================================================================
print("\n 2. 세부 클래스 균등 비율 추출 및 서브셋 구축.")
final_classes = set(CLASS_MAPPING.values())

for main_class in final_classes:
    subfolders = [f for f in os.listdir(EXTRACT_DIR) if f.startswith(main_class) and os.path.isdir(os.path.join(EXTRACT_DIR, f))]

    if not subfolders:
        continue

    num_subfolders = len(subfolders)
    base_quota = 500 // num_subfolders
    remainder = 500 % num_subfolders

    class_sampled_images = []

    for i, folder in enumerate(subfolders):
        folder_path = os.path.join(EXTRACT_DIR, folder)

        sub_images = []
        for ext in ('*.jpg', '*.jpeg', '*.png', '*.JPG', '*.JPEG', '*.PNG'):
            sub_images.extend(glob.glob(os.path.join(folder_path, '**', ext), recursive=True))

        candidate_images = [img for img in sub_images if os.path.getsize(img) > 0]
        quota = base_quota + (1 if i < remainder else 0)
        random.shuffle(candidate_images)

        valid_sampled = []
        for img in candidate_images:
            if len(valid_sampled) == quota:
                break

            try:
                with Image.open(img) as check_img:
                    check_img.verify()
                valid_sampled.append(img)
            except Exception:
                pass

        class_sampled_images.extend(valid_sampled)

    random.shuffle(class_sampled_images)

    for split in ['train', 'val', 'test']:
        split_target_dir = os.path.join(SUBSET_DIR, split, main_class)
        if os.path.exists(split_target_dir):
            shutil.rmtree(split_target_dir)
        os.makedirs(split_target_dir, exist_ok=True)

    total_len = len(class_sampled_images)
    train_bound = int(total_len * 0.8)
    val_bound = int(total_len * 0.9)

    train_imgs = class_sampled_images[:train_bound]
    val_imgs = class_sampled_images[train_bound:val_bound]
    test_imgs = class_sampled_images[val_bound:]

    for img_path in train_imgs:
        shutil.copy(img_path, os.path.join(SUBSET_DIR, 'train', main_class, os.path.basename(img_path)))
    for img_path in val_imgs:
        shutil.copy(img_path, os.path.join(SUBSET_DIR, 'val', main_class, os.path.basename(img_path)))
    for img_path in test_imgs:
        shutil.copy(img_path, os.path.join(SUBSET_DIR, 'test', main_class, os.path.basename(img_path)))

    print(f"[{main_class}] 총 {num_subfolders}개 세부 폴더 균등 추출 완료 (Train:{len(train_imgs)}, Val:{len(val_imgs)}, Test:{len(test_imgs)})")

print("✅ 서브셋 구축 완료.")

# =====================================================================
# [5단계] 가변형 데이터 전처리 및 DataLoader 생성
# =====================================================================
def get_agricultural_transforms(image_size=224):
    base_resize_scale = int(image_size * (256 / 224))
    imagenet_mean = [0.485, 0.456, 0.406]
    imagenet_std = [0.229, 0.224, 0.225]

    train_transform = transforms.Compose([
        transforms.Resize(base_resize_scale),
        transforms.RandomCrop((image_size, image_size)),
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.RandomVerticalFlip(p=0.5),
        transforms.RandomRotation(degrees=15, fill=255),
        transforms.ColorJitter(brightness=0.1, contrast=0.1),
        transforms.ToTensor(),
        transforms.Normalize(mean=imagenet_mean, std=imagenet_std)
    ])

    val_test_transform = transforms.Compose([
        transforms.Resize(base_resize_scale),
        transforms.CenterCrop((image_size, image_size)),
        transforms.ToTensor(),
        transforms.Normalize(mean=imagenet_mean, std=imagenet_std)
    ])

    return train_transform, val_test_transform

def build_dataloaders(subset_dir, image_size=224, batch_size=32):
    train_trf, val_test_trf = get_agricultural_transforms(image_size=image_size)

    train_dataset = datasets.ImageFolder(root=os.path.join(subset_dir, 'train'), transform=train_trf)
    val_dataset = datasets.ImageFolder(root=os.path.join(subset_dir, 'val'), transform=val_test_trf)
    test_dataset = datasets.ImageFolder(root=os.path.join(subset_dir, 'test'), transform=val_test_trf)

    # 로컬 환경에서는 CPU 코어 수에 맞게 num_workers를 조절할 수 있습니다. (보통 4 또는 8)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=4, pin_memory=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=4, pin_memory=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=4, pin_memory=True)

    print(f"\n자동 라벨 인코딩 결과: {train_dataset.class_to_idx}")
    return train_loader, val_loader, test_loader

# ---------------------------------------------------------
# [실행부] 변수 수정
# ---------------------------------------------------------
if __name__ == "__main__":
    TARGET_IMAGE_SIZE = 224
    BATCH_SIZE = 16

    train_loader, val_loader, test_loader = build_dataloaders(
        subset_dir=SUBSET_DIR,
        image_size=TARGET_IMAGE_SIZE,
        batch_size=BATCH_SIZE
    )

    print(f"✅ 딥러닝 모델 학습을 위한 최종 DataLoader 준비 끝. (입력 크기: {TARGET_IMAGE_SIZE}x{TARGET_IMAGE_SIZE})")